audit_header: false
title: Real Estate Video Blog with Jeff Quintin
description: >-
  Our mission at The Quintin Group is to be your best resource for real estate
  advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Home Valuation
    url: 'http://thequintingroup.com/tools-info/how-much-is-your-home-worth/'
  - title: Home Search
    url: 'http://thequintingroup.com/advanced-search/'
  - title: Free Newsletter
    url: /subscribe/
  - title: Get Interviewed
    url: /get-interviewed/
client:
  name: Jeff Quintin
  title:
  license_number:
  about_markdown: >-
    We are proud to have our personal staff contribute to the process of selling
    and or buying your home. Our purpose is to assist you in getting your home
    sold and provide protection of your equity in the time frame you want with
    no inconvenience to you or your family.


    Our staff has one function while they are working for you. This function is
    to “serve you” and make this your most professional selling and buying
    experience. We’ve asked each team member to acquaint themselves with you and
    your property and we want you to utilize each and every service that we
    provide.
  market:
  brand: The Quintin Group
  brokerage: Keller Williams
  phone: (609) 398-5333
  phone_type:
  phone2:
  phone2_type:
  email: Info@TheQuintinGroup.com
  url: 'http://TheQuintinGroup.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://thequintingroup.com/tools-info/how-much-is-your-home-worth/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://thequintingroup.com/advanced-search/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Home Value Report
    CTA_url: 'http://thequintingroup.com/tools-info/how-much-is-your-home-worth/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a Home?
    CTA_text2: Search the entire MLS for your home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'http://thequintingroup.com/advanced-search/'
third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/006.jpg
    CTA_title3: Are you a business owner?
    CTA_text3: Would you like to be interviewed?
    CTA_link_text3: Set Up an Interview
    CTA_url3: /get-interviewed/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/TheQuintinGroup'
  linkedin_url: 'https://www.linkedin.com/in/jeffquintinsuperteam/'
  gplus_url:
  youtube_url: 'https://www.youtube.com/channel/UC9CUnF5stZlAwqT5N_KJ7_g'
  twitter_url: 'http://twitter.com/JeffQuintin'
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Real Estate Podcast with -- CLIENT NAME --
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Real
    Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, home selling tips, home for sale,
    home buying, home buying process, property finder, property search,
    property, real estate market, estate agent, realestate, real estate
    listings, buying a house, homes for sale, mls, home buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text:
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#0981af'
  theme_color: '#020e1b'
  accent_color: '#b40101'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'